import { ILanguageKeys, ILanguageTexts } from "@/types";

export const languageData: {
  [key in ILanguageKeys]: {
    [key in ILanguageTexts]: string;
  };
} = {
  ja_JP: {
    waiting: "待っている",
    expired: "期限切れ",
    in_stock: "在庫あり",
    no_results: "結果なし",
    error: "エラー",
    notes: "注意事項",
    packed: "詰め込まれた",
    supported_prefectures: "対応地域",
    shipping_company: "配送会社",
    shipments: "出荷",
    last_updated: "最終更新日",
    last_fetched: "最後にフェッチされた",
    delivered_at: "配達先",
    track_order: "注文を追跡する",
    track_orders: "注文の追跡",
    tracking_details: "追跡の詳細",
    location: "位置",
    update_tracking_info: "追跡情報を更新する",
    ordered_items: "注文した商品",
    shipping_campaigns: "配送キャンペーン",
    others: "その他",
    message_not_allowed_message: "このメッセージには返信できません。",
    view_messages: "メッセージを表示する",
    expected_delivery_date: "配達予定日",
    processing: "処理",
    admin_cancelled: "管理者がキャンセルしました",
    completed: "完了しました",
    order_placed: "注文完了",
    payment_failed: "支払いに失敗しました",
    seller_acknowledged: "販売者が承認しました",
    shipped: "出荷済み",
    pending_change: "保留中の変更",
    progress: "進捗",
    add_to_indian_shop: "インドのショップに追加",
    add_to_nepal_shop: "ネパールショップに追加",
    related_items: "関連商品",
    order_change_request_message:
      "注文変更リクエストがユーザーに送信されました。",
    order_changes_accepted_message:
      "ユーザーによる注文の変更は受け付けられました。",
    stock_update_desc: "このアイテムの新しい在庫を入力してください。",
    request_change: "変更のリクエスト",
    acknowledge: "認める",
    order_change_acknowledged_request:
      "このアクションは、ユーザーに注文のさらなる変更を要求します。",
    order_change_acknowledged_desc:
      "このアクションにより、注文変更リクエストが承認されます。",
    update_stock: "在庫を更新する",
    select_date: "日付を選択",
    thumbnail_error_message: "サムネイルを選択してもう一度お試しください",
    manage_images: "画像の管理",
    camera_permission_message:
      "申し訳ありませんが、これを機能させるにはカメラの許可が必要です。",
    deleting: "削除する",
    uploading: "アップロードする",
    item_weight_error_message: "体重は25を超えてはなりません",
    package_image_uploading_message:
      "画像のアップロードが完了するまでお待ちください",
    logout_alert: "ログアウトしてもよろしいですか?",
    delivery_update_success_message: "配達時間が正常に更新されました",
    flat_amount: "一律金額",
    flat_discount: "一律割引",
    campaign_discount_error: "一律送料割引は 0 より大きくする必要があります",
    campaign_shipping_charge_error: "一律送料は0より大きくなければなりません",
    campaign_discount_percentage_error: "割引は 0 より大きくなければなりません",
    reset_company_title: "この会社をリセットしてもよろしいですか?",
    reset_company_description: "リセットする会社を選択してください",
    fields_auto_filled: "フィールドは自動入力されます",
    fetching_address_info: "アドレス情報を取得しています...",
    prefecture_error: "指定された郵便番号の都道府県が一致しません",
    expiry_threshold: "有効期限のしきい値",
    something_went_wrong: "何か問題が発生しました!!",
    day: "日",
    days: "日々",
    default: "デフォルト",
    back: "戻る",
    total_weight: "総重量",
    delivery_time_slots: "配達時間帯",
    download: "ダウンロード",
    Loading: "読み込み中...",
    transaction_type: "取引タイプ",
    send_message: "メッセージを送る",
    update_profile: "プロフィールを更新する",
    add_item_variation: "アイテムバリエーションを追加",
    item_variations: "アイテムバリエーション",
    mfg_date: "Mfg Date",
    no_item_variations: "アイテムバリエーションなし",
    exp_date: "Exp Date",
    selected: "選択された",
    disabled: "非活性",
    order_amount_threshold: "注文金額のしきい値",
    message: "メッセージ",
    enabled: "有効",
    sent_by_admin: "管理者によって送信されました",
    edit_message: "メッセージを編集する",
    variation_name: "バリエーション名",
    selling_price: "販売価格",
    type_here_to_reply: "返信するにはここに入力してください...",
    cannot_reply: "現在この注文に返信することはできません",
    shop_registration_number: "店舗登録番号",
    send_message_to_user: "ユーザーにメッセージを送信する",
    item_price_after_tax: "価格（税込",
    price_header: "価格",
    edit_variation: "バリエーションを編集する",
    item_status: "アイテムのステータス",
    marked_price_header: "標準価格",
    items: "商品",
    welcome_text: "販売者管理画面へようこそ",
    login: "ログイン",
    email: "Eメール",
    password: "パスワード",
    email_required: "Eメールアドレスは入力必須です",
    password_required: "パスワードは入力必須です",
    shipping_fees: "送料",
    shop_users: "ショップユーザー",
    delete: "消去",
    logout: "ログアウト",
    recommended_items: "おすすめアイテム",
    low_stock_items: "在庫残りわずか",
    expired_items: "消費期限切れ",
    packages: "パッケージ",
    search_items: "品名または説明文で検索",
    category: "カテゴリー",
    rows_per_page: "1ページあたり行数 : ",
    total: "合計",
    view_all: "すべて見る",
    promotional_message: "プロモーションメッセージ",
    english_item_name_required: "品名の英語入力は必須です",
    english_item_description_required: "説明文の英語入力は必須です",
    english_item_shipping_time_required: "配送に必要な日数の英語入力は必須です",
    ne_item_name_required: "品名のネパール語入力は必須です",
    ne_item_description_required: "説明文のネパール語入力は必須です",
    ne_item_shipping_time_required: "配送日数のネパール語入力は必須です",
    jp_item_name_required: "品名の日本語入力は必須です",
    add_images: "画像の追加",
    jp_item_description_required: "説明文の日本語入力は必須です",
    jp_item_shipping_time_required: "配送日数の日本語入力は必須です",
    vn_item_name_required: "品名のベトナム語入力は必須です",
    vn_item_description_required: "説明文のベトナム語入力は必須です",
    vn_item_shipping_time_required: "配送日数のベトナム語入力は必須です",
    item_stock_negative: "商品在庫をマイナスにすることはできません",
    item_price_negative: "商品価格をマイナスにすることはできません",
    item_price_required: "商品価格の入力は必須です",
    item_expired_date_required: "商品の消費期限入力は必須です",
    item_manufactured_date_required: "製造年月日の入力は必須です",
    item_category_required: "商品カテゴリーの入力は必須です",
    item_type_required: "商品タイプの入力は必須です",
    item_weight_negative: "商品重量をマイナスにすることはできません",
    item_weight_required: "商品重量の入力は必須です",
    item_image_length: "商品画像の掲載上限は4枚です",
    item_marked_price_negative:
      "標準価格を、通常価格より低くすることはできません",
    item_marked_price_less_than_price:
      "表示価格は販売価格より低くすることはできません",
    item_marked_price_zero: "標準価格を、0円にすることはできません",
    en_item_name: "商品名（英語）",
    en_item_name_placeholder: "品名を英語で入力",
    en_shipping_time: "配送日数（英語）",
    en_shipping_time_placeholder: "配送日数を英語で入力",
    en_tags: "タグ（英語）",
    en_tags_placeholder: "タグを英語で入力",
    en_description: "説明文（英語）",
    en_description_placeholder: "説明文を英語で入力",
    ne_item_name: "商品名（ネパール語）",
    ne_item_name_placeholder: "品名をネパール語で入力",
    ne_shipping_time: "配送日数（ネパール語）",
    ne_shipping_time_placeholder: "配送日数をネパール語で入力",
    ne_tags: "タグ（ネパール語）",
    ne_tags_placeholder: "タグをネパール語で入力",
    ne_description: "説明文（ネパール語）",
    ne_description_placeholder: "説明文をネパール語で入力",
    jp_item_name: "商品名（日本語）",
    jp_item_name_placeholder: "品名を日本語で入力",
    jp_shipping_time: "配送日数（日本語）",
    jp_shipping_time_placeholder: "配送日数を日本語で入力",
    jp_tags: "タグ（日本語）",
    jp_tags_placeholder: "タグを日本語で入力",
    no_message_availabe_for_this_shop:
      "このショップに関するメッセージはありません",
    jp_description: "説明文（日本語）",
    jp_description_placeholder: "説明文を日本語で入力",
    vn_item_name: "商品名（ベトナム語）",
    vn_item_name_placeholder: "品名をベトナム語で入力",
    vn_shipping_time: "配送日数（ベトナム語）",
    vn_shipping_time_placeholder: "配送日数をベトナム語で入力",
    max_quantity: "最大数量",
    vn_tags: "タグ（ベトナム語）",
    vn_tags_placeholder: "タグをベトナム語で入力",
    vn_description: "説明文（ベトナム語）",
    vn_description_placeholder: "説明文をベトナム語で入力",
    en: "英語",
    confirm_your_action: "",
    en_placeholder: "詳細を英語で入力",
    np: "ネパール語",
    np_placeholder: "詳細をネパール語で入力",
    jp: "日本語",
    jp_placeholder: "詳細を日本語で入力",
    vn: "ベトナム語",
    vn_placeholder: "詳細をベトナム語で入力",
    item_price: "商品価格",
    is_discounted_price: "これは値引き価格でしょうか？",
    item_marked_price: "標準価格",
    item_marked_price_without_tax: "標準価格（税抜）",
    item_stock: "商品在庫",
    can_be_merged: "この商品は冷蔵タイプでも配送可能ですか?",
    select_here: "ここを選択",
    yes: "はい",
    no: "いいえ",
    item_expired_date: "商品の消費期限",
    item_expired_date_placeholder: "商品の消費期限を入力",
    item_manufactured_date: "製造年月日",
    item_manufactured_date_placeholder: "商品の製造年月日を入力",
    item_sku: "商品SKU",
    all_items: "全てのアイテム",
    item_sku_placeholder: "商品SKUを入力",
    item_weight_in_kg: "商品重量(kg)",
    item_weight_in_kg_placeholder: "商品重量(kg)を入力",
    select_category: "カテゴリーを選択",
    clear: "クリア",
    cool: "冷蔵",
    dry: "ドライ",
    frozen: "冷凍",
    item_type: "商品タイプ",
    enter_your_message: "メッセージを入力してください",
    choose_image: "画像を選択",
    alcohol: "アルコール",
    uplaod_image: "画像のアップロード",
    update: "更新",
    add: "追加",
    update_item: "商品を更新",
    add_item: "商品を追加",
    update_thumbnail: "サムネイルを更新",
    try_changing_shop: "店を変えてみる",
    delete_item: "商品を削除",
    delete_item_confirmation: "この商品を削除しますか？",
    delete_item_success_message: "商品が正常に削除されました",
    recommended_items_add_success_message: "お勧め商品が正常に追加されました",
    recommended_items_remove_success_message:
      "お勧め商品が正常に削除されました",
    recommended_confirmation_message:
      "この商品を「お勧め商品」に追加しますか？",
    recommended__remove_confirmation_message:
      "この商品をお勧め品から削除してもよろしいですか？",
    confirm_message: "アクションの確認をお願いします",
    total_packages: "パッケージの合計数",
    add_package: "パッケージの追加",
    delete_package: "パッケージの削除",
    search: "検索",
    order_items: "注文した商品",
    package_description: "パッケージの内容",
    package_name: "パッケージ名",
    package_price: "パッケージ価格",
    select_package_quantity: "数量を選択してください。 ",
    update_address: "住所を更新する",
    filter: "フィルター：",
    select_shop: "店舗を選択",
    select_language: "言語を選択",
    english: "英語",
    nepali: "ネパール語",
    japanese: "日本語",
    vietnamese: "ベトナム語",
    description: "商品説明",
    marked_price: "標準価格",
    name: "品名",
    price: "価格",
    low_stock: "在庫が少ない",
    item_price_before_tax: "税抜価格",
    shipping_time: "配送日数",
    tags: "タグ",
    type: "タイプ",
    weight_in_kg: "重量 (kg)",
    comments: "コメント",
    comment: "コメントする",
    comment_placeholder: "コメントを入力",
    comment_required: "コメントの入力は必須です",
    orders: "受注状況",
    order: "注文",
    order_id_search: "注文IDで検索",
    view: "詳細を見る",
    quantity: "数量",
    order_info: "注文情報",
    address1: "アドレス1",
    address2: "アドレス2",
    city: "市町村",
    delivery_time: "お届け予定日",
    cancelled: "キャンセル",
    extra_fee: "追加料金",
    order_type: "配送温度タイプ",
    customer_name: "顧客名",
    customer_phone: "顧客の電話番号",
    are_you_sure_you_want_to_delete_this_item:
      "この項目を削除してもよろしいですか?",
    order_status: "注文状況",
    payment_type: "お支払方法",
    postal_code: "郵便番号",
    prefecture: "都道府県",
    redeemed_points: "ポイント還元",
    total_item_price: "商品合計価格",
    total_price: "合計価格",
    total_shipping_price: "送料の合計額",
    hide_items: "商品をを隠す",
    shipping_address: "配送先住所",
    show_items: "商品表示",
    view_invoice: "インボイスの確認",
    print_invoice: "インボイスの印刷",
    generate_invoice_of_order: "インボイスを作成する",
    change_status: "ステータスを変更する",
    change: "変更する",
    submit: "送信",
    tracking_number: "追跡番号",
    alert_user: "ユーザーが配送先住所の更新をリクエストしました",
    enter_your_comment: "コメントを入力してください",
    tracking_number_placeholder: "追跡番号の入力",
    tracking_placeholder: "追跡URLの入力",
    tracking_url: "追跡URL",
    profile: "プロフィール",
    update_tracting_info: "追跡情報の更新",
    confirm: "確認",
    reset_shipping_fee: "送料をリセット",
    reseting: "リセット",
    copy: "アイテムをコピーする",
    select_shipping_company: "配送会社を選択してください",
    operation_successfull: "操作が成功しました",
    user_profile: "ユーザープロフィール",
    change_password: "パスワードの変更",
    enter_tracking_number: "追跡番号を入力してください",
    enter_tracking_url: "トラッキングURLを入力してください",
    change_profile: "プロフィールを変更",
    address_update_request: "アドレス更新リクエスト",
    update_profile_picture: "プロフィール写真の更新",
    phone_number: "電話番号",
    updating: "更新中",
    shop_info: "店舗情報",
    edit_shop: "店舗情報の編集",
    shop_name: "店å舗名",
    no_of_orders: "注文数",
    shop_active: "店舗の公開状況",
    shop_address: "店舗の住所",
    shop_country: "店舗の対象国",
    enter_variation_price: "変動価格を入力してください",
    shop_facebook_link: "店舗のFacebookリンク",
    shop_introduction: "店舗紹介",
    shop_phone_number: "店舗の電話番号",
    shop_postal_code: "店舗の郵便番号",
    shop_tiktok_link: "店舗のTiktokリンク",
    shop_no_of_users: "店舗のユーザー数",
    please_confirm_your_action: "アクションの確認をお願いします",
    cool_shipping_fee: "クール 冷蔵",
    dry_shipping_fee: "常温",
    from_area: "発送元",
    frozen_shipping_fee: "クール 冷凍",
    enter_variation_weight: "バリエーションの重みを入力してください",
    to_area: "発送先",
    pay_pay: "ペイペイ",
    weight: "重量",
    actions: "アクション",
    approved: "承認状況",
    campaigns: "キャンペーン",
    created: "作成完了日時",
    pending: "保留中",
    seller_email: "販売者のメールアドレス",
    seller_name: "販売者氏名",
    edit: "編集",
    seller_phone: "販売者電話番号",
    seller_id: "販売者ID",
    seller_role: "販売者の役割",
    enter_item_description: "アイテムの説明を入力してください",
    enter_item_name: "項目名を入力してください",
    enter_item_stock: "アイテムの在庫を入力してください",
    enter_item_tags: "項目タグをカンマ（,）で区切って入力してください",
    enter_item_weight: "アイテムの重量を入力してください",
    enter_marked_price: "マークされた価格を入力してください",
    enter_selling_price: "販売価格を入力してください",
    enter_sku: "SKUを入力してください",
    change_langauge: "言語を変えてください",
    stock: "在庫",
    id: "ID",
    you: "君",
    recommended: "お勧め",
    sale: "割引率",
    expiry_date: "消費期限",
    items_count: "品数",
    date: "日付",
    payment_method: "お支払い方法",
    status: "ステータス",
    address: "住所",
    role: "管理権限",
    filter_by_status: "ステータスで絞り込み",
    admin_cancel: "管理者によるキャンセル",
    all: "すべて",
    cancel: "キャンセル",
    done: "完了",
    variation_price: "変動価格",
    variation_stock: "バリエーションストック",
    variation_weight: "バリエーションウェイト",
    processed: "発送またはキャンセル済",
    wait_payment: "支払いを待っています",
    clear_filters: "フィルターをクリアする",
    update_variation: "アップデートバリエーション",
    wait_review: "レビュー待ち",
    wait_shipping: "発送待ち",
    available_delivery_time: "配達可能時間",
    convenience_store: "コンビニエンスストア払い",
    cash_on_delivery: "代金引換",
    credit_card: "クレジットカード",
    confirm_password: "パスワードを確認する",
    new_password: "新パスワード",
    search_messages: "メッセージの検索",
    old_password: "旧パスワード",
    new_password_is_required: "新パスワードは必須です",
    old_password_is_required: "旧パスワードは必須です",
    password_expired_confirmation:
      "パスワードの有効期限が切れています。新しいパスワードを設定してください、",
    password_regex:
      "大文字、小文字、数字、記号が１つ以上含まれるパスワードを設定してください",
    password_8_char: "パスワードは８文字以上で設定してください",
    passwords_do_not_match: "パスワードが一致しません",
    edit_shop_legal_info: "ショップの特定商取引法表示を編集する",
    order_review: "注文レビュー",
    review: "レビュー",
    rating: "評価",
    with_tax: "(税込)",
    discount: "割引",
    tax: "税金",
    my_recommended_items: "私のおすすめアイテム",
    total_orders: "総注文数",
    total_revenue: "総収入",
    view_orders: "注文を見る",
    critical_items: "重要なアイテム",
    search_by_name_or_description: "名前または説明で検索",
    updated: "更新しました",
    added: "追加した",
    item_information: "アイテム情報",
    item_category: "アイテムカテゴリ",
    item_weight: "アイテムの重量",
    enter_variation_stock: "バリエーション在庫を入力してください",
    sku: "SKU",
    item_tags: "アイテムタグ（オプション）",
    manufacture_date: "製造年月日",
    item_name: "項目名",
    item_description: "アイテム説明",
    order_search_placeholder: "注文を検索する",
    reset: "リセット",
    start_date: "開始日",
    end_date: "終了日",
    apply: "適用する",
    send_link: "リンクを送る",
    select: "選択する",
    minimum_order_amount: "最低注文金額",
    waiting_delivery: "配達待ち",
    order_id: "注文ID",
    order_date: "注文日",
    forgot_password: "パスワードをお忘れですか?",
    delivery_address: "配送先住所",
    sub_total: "小計",
    recent_messages: "最近のメッセージ",
    total_for: "の合計",
    ship_order: "出荷命令",
    total_items: "総アイテム数",
    supported_areas: "対応エリア",
    close: "近い",
    save: "保存",
    no_campaigns: "キャンペーンはありません",
    campaign_name: "キャンペーン名",
    campaign_discount: "キャンペーン割引",
    campaign_description: "キャンペーンの説明",
    given_by: "によって与えられた",
    threshold: "しきい値",
    discount_type: "割引タイプ",
    available_deliveries: "利用可能な配達",
    active: "アクティブ",
    disable: "無効にする",
    shipping_fee_with_tax: "税込送料",
    select_shipping_area: "配送エリアを選択してください",
    shipping_campaign: "送料キャンペーン",
    terms_condition: "利用規約",
    privacy_policy: "プライバシーポリシー",
    home: "家",
    my_items: "私のアイテム",
    not_confirmed: "確認されていません",
    optional: "オプション",
    can_be_sent_in_cool_cart: "クールカートで発送可能?",
    enter_variation_name: "バリエーション名を入力してください",
    messages: "メッセージ",
    message_user: "メッセージユーザー",
    before_tax: "税引き前",
    add_variation: "バリエーションを追加する",
    alert_seller: "ユーザーに配送先住所の更新を要求しました",
    low_stock_threshold: "在庫閾値が低い",
    choose_from_gallery: "ギャラリーから選ぶ",
    open_camera: "オープンカメラ",
    approve: "承認する",
    discounted_shipping: "割引配送",
    discounted_shipping_error_message:
      "割引配送は重量2kgまでの商品にのみ適用されます",
  },
  vi_VN: {
    waiting: "Chờ",
    expired: "Hết hạn",
    in_stock: "Còn hàng",
    no_results: "Không có kết quả",
    error: "Lỗi",
    notes: "Ghi chú",
    packed: "Đóng gói",
    supported_prefectures: "Khu vực được hỗ trợ",
    shipping_company: "Công ty vận chuyển",
    shipments: "Lô hàng",
    last_fetched: "Tìm nạp lần cuối",
    delivered_at: "Giao tại",
    last_updated: "Cập nhật lần cuối",
    tracking_details: "Penerang Ngesan",
    track_orders: "Jejak Pesan",
    track_order: "Jejak Pesan",
    location: "Vị trí",
    update_tracking_info: "Cập nhật thông tin theo dõi",
    ordered_items: "Các mặt hàng đã đặt hàng",
    shipping_campaigns: "Chiến dịch vận chuyển",
    others: "Người khác",
    message_not_allowed_message: "BẠN KHÔNG THỂ TRẢ LỜI TIN NHẮN NÀY!",
    view_messages: "Xem tin nhắn",
    expected_delivery_date: "Ngày giao hàng dự kiến",
    processing: "Xử lý",
    admin_cancelled: "Quản trị viên đã hủy",
    completed: "Hoàn thành",
    payment_failed: "Thanh toán không thành công",
    seller_acknowledged: "Người bán đã xác nhận",
    shipped: "Đã vận chuyển",
    order_placed: "Đặt hàng",
    pending_change: "Thay đổi đang chờ xử lý",
    progress: "Tiến triển",
    add_to_indian_shop: "Thêm vào cửa hàng Ấn Độ",
    add_to_nepal_shop: "Thêm vào cửa hàng nepal",
    related_items: "Những món đồ liên quan",
    order_change_request_message:
      "Yêu cầu thay đổi thứ tự đã được gửi tới người dùng.",
    order_changes_accepted_message:
      "Những thay đổi đối với đơn đặt hàng của người dùng đã được chấp nhận.",
    stock_update_desc: "Nhập kho mới cho mặt hàng này.",
    acknowledge: "Thừa nhận",
    request_change: "Yêu cầu thay đổi",
    order_change_acknowledged_request:
      "Hành động này sẽ yêu cầu người dùng thực hiện thêm các thay đổi trong đơn đặt hàng.",
    order_change_acknowledged_desc:
      "Hành động này sẽ phê duyệt yêu cầu thay đổi đơn hàng.",
    update_stock: "cập nhật kho",
    select_date: "chọn ngày",
    thumbnail_error_message: "Vui lòng chọn hình thu nhỏ và thử lại",
    manage_images: "Quản lý hình ảnh",
    camera_permission_message:
      "Rất tiếc, chúng tôi cần quyền truy cập vào máy ảnh để thực hiện công việc này!",
    deleting: "xóa",
    uploading: "đang tải lên",
    item_weight_error_message: "Trọng lượng không được lớn hơn 25",
    package_image_uploading_message:
      "Vui lòng đợi trong khi tải hình ảnh lên hoàn tất",
    logout_alert: "Bạn có chắc chắn bạn muốn thoát?",
    delivery_update_success_message:
      "Thời gian giao hàng được cập nhật thành công",
    flat_amount: "Số lượng căn hộ",
    flat_discount: "Giảm giá cố định",
    campaign_discount_error: "Giảm giá vận chuyển cố định phải lớn hơn 0",
    campaign_shipping_charge_error: "Phí vận chuyển cố định phải lớn hơn 0",
    campaign_discount_percentage_error: "Mức giảm giá phải lớn hơn 0",
    reset_company_description:
      "Bạn có chắc chắn muốn thiết lập lại công ty này không?",
    reset_company_title: "Chọn công ty để đặt lại",
    fields_auto_filled: "các trường được tự động điền",
    fetching_address_info: "đang tìm nạp thông tin địa chỉ...",
    prefecture_error: "Tỉnh của mã bưu chính đã cho không khớp",
    something_went_wrong: "Đã xảy ra lỗi!!",
    days: "ngày",
    day: "ngày",
    expiry_threshold: "Ngưỡng hết hạn",
    open_camera: "Mở máy ảnh",
    choose_from_gallery: "Chọn từ phòng trưng bày",
    enter_item_description: "nhập mô tả mục",
    enter_item_name: "nhập tên mục",
    enter_item_stock: "nhập kho hàng",
    enter_item_tags: "nhập các thẻ mục được phân tách bằng dấu phẩy (,)",
    enter_item_weight: "nhập trọng lượng món hàng",
    enter_marked_price: "nhập giá đánh dấu",
    enter_selling_price: "nhập giá bán",
    approve: "chấp thuận",
    enter_sku: "nhập mã hàng",
    alert_seller: "Bạn đã yêu cầu người dùng cập nhật địa chỉ giao hàng của họ",
    default: "Mặc định",
    address_update_request: "yêu cầu cập nhật địa chỉ",
    back: "Mặt sau",
    send_link: "Gửi link",
    forgot_password: "Quên mật khẩu?",
    low_stock_threshold: "ngưỡng tồn kho thấp",
    promotional_message: "tin nhắn quảng cáo",
    before_tax: "Trước thuế",
    alcohol: "Rượu bia",
    recent_messages: "Tin nhắn gần đây",
    delivery_time_slots: "Khoảng thời gian giao hàng",
    download: "Tải xuống",
    transaction_type: "Loại giao dịch",
    Loading: "Đang tải...",
    send_message: "Gửi tin nhắn",
    update_profile: "Cập nhật hồ sơ",
    try_changing_shop: "Hãy thử thay đổi cửa hàng",
    no_message_availabe_for_this_shop: "KHÔNG CÓ TIN NHẮN CHO CỬA HÀNG NÀY",
    pay_pay: "Pay Pay",
    edit_variation: "biên tập biến thể",
    enter_your_message: "Nhập tin nhắn của bạn",
    can_be_sent_in_cool_cart: "Giỏ hàng mát mẻ",
    exp_date: "Ngày hết HSD ",
    profile: "Hồ sơ",
    add_variation: "Thêm biến thể",
    enter_variation_name: "Tên",
    mfg_date: "Ngày SX",
    add_item_variation: "Thêm phân loại theo trọng lượng",
    not_confirmed: "Chưa xác nhận",
    selected: "đã chọn",
    disabled: "Ẩn (tắt) mặt hàng này",
    alert_user: "Người dùng đã yêu cầu cập nhật địa chỉ giao hàng của họ",
    edit: "Chỉnh sửa",
    order_amount_threshold: "Ngưỡng số tiền đặt hàng",
    sent_by_admin: "Gửi bởi quản trị viên",
    message: "tin nhắn",
    enabled: "Đã bật",
    item_status: "Trạng thái mặt hàng",
    edit_message: "chỉnh sửa tin nhắn",
    type_here_to_reply: "Nhập vào đây để trả lời...",
    cannot_reply: "Bạn không thể trả lời đơn đặt hàng này bây giờ",
    order: "đặt hàng",
    send_message_to_user: "Gửi tin nhắn cho người dùng",
    item_price_after_tax: "Giá (Đã bao gồm thuế)",
    marked_price_header: "Giá trên nhãn",
    price_header: "Giá",
    admin_cancel: "admin_cancel",
    all: "Tất cả",
    cancel: "Hủy",
    done: "Hoàn thành",
    filter_by_status: "Tìm kiếm theo tình trạng đơn hàng",
    processed: "Đã xử lý xong",
    wait_payment: "Đang chờ thanh toán",
    wait_review: "Chờ đánh giá",
    wait_shipping: "Chờ giao hàng",
    items: "Mặt hàng",
    welcome_text: "Chào mừng đến với Trang quản trị tài khoản Người bán",
    login: "Đăng nhập",
    email: "Email",
    password: "Mật khẩu",
    email_required: "Vui lòng nhập email",
    password_required: "Vui lòng nhập mật khẩu",
    shipping_fees: "Phí vận chuyển",
    shop_users: "Tài khoản truy cập",
    logout: "Đăng xuất",
    item_variations: "Phân loại theo trọng lượng",
    recommended_items: "Mặt hàng phổ biến được đề xuất",
    low_stock_items: "Mặt hàng sắp hết",
    expired_items: "Hết HSD",
    packages: "Gói hàng",
    search_items: "Tìm theo Tên hoặc Chi tiết sản phẩm",
    category: "Danh mục",
    rows_per_page: "Số dòng mỗi trang: ",
    all_items: "Tất cả món đồ",
    total: "Tổng cộng đơn hàng",
    english_item_name_required: "Vui lòng nhập Tên sản phẩm (Tiếng Anh)",
    english_item_description_required:
      "Vui lòng nhập Chi tiết sản phẩm (Tiếng Anh)",
    english_item_shipping_time_required:
      "Vui lòng nhập Thời gian giao hàng (Tiếng Anh)",
    ne_item_name_required: "Vui lòng nhập Tên sản phẩm (Tiếng Nepal)",
    ne_item_description_required:
      "Vui lòng nhập Chi tiết sản phẩm (Tiếng Nepal)",
    ne_item_shipping_time_required:
      "Vui lòng nhập Thời gian giao hàng (Tiếng Nepal)",
    jp_item_name_required: "Vui lòng nhập Tên sản phẩm (Tiếng Nhật)",
    jp_item_description_required:
      "Vui lòng nhập Chi tiết sản phẩm (Tiếng Nhật)",
    jp_item_shipping_time_required:
      "Vui lòng nhập Thời gian giao hàng (Tiếng Nhật)",
    vn_item_name_required: "Vui lòng nhập Tên sản phẩm (Tiếng Việt)",
    vn_item_description_required:
      "Vui lòng nhập Chi tiết sản phẩm (Tiếng Việt)",
    vn_item_shipping_time_required:
      "Vui lòng nhập Thời gian giao hàng (Tiếng Việt)",
    item_stock_negative: "Tồn kho không được là số âm",
    item_price_negative: "Giá bán không được là số âm",
    item_price_required: "Vui lòng nhập Giá bán",
    clear: "thông thoáng",
    item_expired_date_required: "Vui lòng nhập Ngày hết hạn sử dụng",
    item_manufactured_date_required: "Vui lòng nhập Ngày sản xuất",
    item_category_required: "Vui lòng chọn Phân loại",
    item_type_required: "Vui lòng chọn Loại mặt hàng",
    item_tags: "thẻ mục (tùy chọn)",
    variation_name: "Tên biến thể",
    search_messages: "Tìm kiếm tin nhắn",
    variation_price: "Giá biến đổi",
    variation_stock: "Cổ phiếu biến thể",
    variation_weight: "Trọng lượng biến thể",
    item_weight_negative: "Trọng lượng không được là số âm",
    item_weight_required: "Vui lòng nhập Trọng lượng sản phẩm",
    item_image_length: "Bạn chỉ được thêm tối đa 4 ảnh",
    item_marked_price_negative: "Giá trên nhãn không được là số âm",
    item_marked_price_less_than_price:
      "Giá đánh dấu không thể thấp hơn giá bán",
    item_marked_price_zero: "Giá trên nhãn không được bằng 0",
    en_item_name: "Tên sản phẩm (Tiếng Anh)",
    en_item_name_placeholder: "Nhập Tên sản phẩm (Tiếng Anh)",
    en_shipping_time: "Thời gian giao hàng (Tiếng Anh)",
    en_shipping_time_placeholder: "Nhập Thời gian giao hàng (Tiếng Anh)",
    en_tags: "Thẻ tag (Tiếng Anh)",
    en_tags_placeholder: "Nhập Thẻ tag (Tiếng Anh)",
    en_description: "Chi tiết sản phẩm (Tiếng Anh)",
    en_description_placeholder: "Nhập Chi tiết sản phẩm (Tiếng Anh)",
    ne_item_name: "Tên sản phẩm (Tiếng Nepal)",
    ne_item_name_placeholder: "Nhập Tên sản phẩm (Tiếng Nepal)",
    ne_shipping_time: "Thời gian giao hàng (Tiếng Nepal)",
    ne_shipping_time_placeholder: "Nhập Thời gian giao hàng (Tiếng Nepal)",
    ne_tags: "Thẻ tag (Tiếng Nepal)",
    ne_tags_placeholder: "Nhập Thẻ tag (Tiếng Nepal)",
    ne_description: "Chi tiết sản phẩm (Tiếng Nepal)",
    ne_description_placeholder: "Nhập Chi tiết sản phẩm (Tiếng Nepal)",
    jp_item_name: "Tên sản phẩm (Tiếng Nhật)",
    jp_item_name_placeholder: "Nhập Tên sản phẩm (Tiếng Nhật)",
    jp_shipping_time: "Thời gian giao hàng (Tiếng Nhật)",
    jp_shipping_time_placeholder: "Nhập Thời gian giao hàng (Tiếng Nhật)",
    jp_tags: "Thẻ tag (Tiếng Nhật)",
    jp_tags_placeholder: "Nhập Thẻ tag (Tiếng Nhật)",
    jp_description: "Chi tiết sản phẩm (Tiếng Nhật)",
    jp_description_placeholder: "Nhập Chi tiết sản phẩm (Tiếng Nhật)",
    vn_item_name: "Tên sản phẩm (Tiếng Việt)",
    vn_item_name_placeholder: "Nhập Tên sản phẩm (Tiếng Việt)",
    vn_shipping_time: "Thời gian giao hàng (Tiếng Việt)",
    vn_shipping_time_placeholder: "Nhập Thời gian giao hàng (Tiếng Việt)",
    vn_tags: "Thẻ tag (Tiếng Việt)",
    vn_tags_placeholder: "Nhập Thẻ tag (Tiếng Việt)",
    vn_description: "Chi tiết sản phẩm (Tiếng Việt)",
    vn_description_placeholder: "Nhập Chi tiết sản phẩm (Tiếng Việt)",
    en: "Tiếng Anh",
    en_placeholder: "Nhập Chi tiết bằng Tiếng Anh",
    np: "Tiếng Nepal",
    np_placeholder: "Nhập Chi tiết bằng Tiếng Nepal",
    jp: "Tiếng Nhật",
    jp_placeholder: "Nhập Chi tiết bằng Tiếng Nhật",
    message_user: "Người dùng tin nhắn",
    vn: "Tiếng Việt",
    vn_placeholder: "Nhập Chi tiết bằng Tiếng Việt",
    item_price: "Giá bán",
    update_variation: "Cập nhật biến thể",
    is_discounted_price: "Đây có phải là Giá ưu đãi không?",
    item_marked_price: "Giá trên nhãn",
    item_marked_price_without_tax: "Giá trên nhãn (chưa bao gồm thuế)",
    item_stock: "Số tồn kho",
    can_be_merged: "Sản phẩm này có thể gộp chung đơn với sản phẩm khác không?",
    select_here: "Nhấn để chọn",
    yes: "Được",
    no: "Không",
    item_expired_date: "Ngày hết hạn sử dụng",
    item_expired_date_placeholder: "Nhập Ngày hết hạn sử dụng",
    item_manufactured_date: "Ngày sản xuất",
    item_manufactured_date_placeholder: "Nhập Ngày sản xuất",
    item_sku: "Mã phân loại hàng hóa (SKU)",
    item_sku_placeholder: "Nhập số SKU",
    item_weight_in_kg: "Trọng lượng (Kg)",
    item_weight_in_kg_placeholder: "Nhập Trọng lượng (Kg)",
    select_category: "Chọn Phân loại",
    cool: "Trữ mát",
    dry: "Hàng khô",
    frozen: "Trữ đông",
    item_type: "Loại mặt hàng",
    choose_image: "Chọn ảnh",
    clear_filters: "xóa bộ lọc",
    uplaod_image: "Tải ảnh",
    update: "Cập nhật",
    add: "Thêm",
    low_stock: "Hết hàng/ Tồn kho thấp",
    update_item: "Cập nhật chi tiết",
    add_item: "Thêm mặt hàng",
    update_thumbnail: "Cập nhật ảnh đại diện",
    total_weight: "Tổng khối lượng",
    max_quantity: "Số lượng tối đa",
    delete_item: "Xóa",
    delete_item_confirmation: "Bạn có muốn xóa sản phẩm này không?",
    delete_item_success_message: "Đã xóa sản phẩm",
    recommended_items_add_success_message: "Đã thêm vào Mặt hàng được đề xuất",
    recommended_items_remove_success_message:
      "Đã xóa khỏi Mặt hàng được đề xuất",
    recommended_confirmation_message:
      "Bạn có muốn thêm sản phẩm này vào Mặt hàng được đề xuất?",
    recommended__remove_confirmation_message:
      "Bạn có muốn xóa sản phẩm này khỏi Mặt hàng được đề xuất?",
    confirm_message: "Hãy xác nhận thao tác",
    total_packages: "Tổng số Gói hàng",
    enter_your_comment: "nhập bình luận của bạn...",
    add_package: "Thêm Gói hàng",
    delete_package: "Xóa Gói hàng",
    search: "Tìm kiếm",
    package_description: "Chi tiết Gói hàng",
    package_name: "Tên Gói hàng",
    package_price: "Giá Gói hàng",
    select_package_quantity: "Chọn số lượng ",
    filter: "Tìm kiếm :,Tìm kiếm,Xóa",
    select_shop: "Chọn gian hàng",
    select_language: "Chọn ngôn ngữ",
    english: "Tiếng Anh",
    nepali: "Tiếng Nepal",
    japanese: "Tiếng Nhật",
    vietnamese: "Tiếng Việt",
    description: "Chi tiết sản phẩm",
    marked_price: "Giá trên nhãn",
    name: "Tên",
    price: "Giá bán (cao - thấp)",
    item_price_before_tax: "Giá bán trước thuế",
    shipping_time: "Thời gian giao hàng",
    tags: "Thẻ tag (không bắt buộc)",
    type: "Loại",
    change_langauge: "Thay đổi ngôn ngữ",
    weight_in_kg: "Trọng lượng (Kg)",
    comments: "Xem bình luận của khách",
    comment: "Bình luận",
    enter_tracking_number: "nhập số theo dõi",
    enter_tracking_url: "nhập url theo dõi",
    comment_placeholder: "Nhập nội dung bình luận",
    comment_required: "Vui lòng nhập bình luận",
    orders: "Đơn hàng",
    order_id_search: "Tìm theo số ID đơn hàng",
    view: "Chi tiết",
    quantity: "Số lượng",
    order_info: "Chi tiết đơn hàng",
    address1: "Địa chỉ 1",
    address2: "Địa chỉ 2",
    city: "Thành phố",
    delivery_time: "Thời gian giao hàng",
    extra_fee: "Phụ phí",
    order_type: "Loại đơn hàng",
    customer_name: "Tên khách hàng",
    customer_phone: "điện thoại của khách hàng",
    order_status: "Tình trạng đơn hàng",
    payment_type: "Phương thức thanh toán",
    postal_code: "Mã bưu chính",
    prefecture: "Tỉnh",
    available_delivery_time: "thời gian giao hàng có sẵn",
    redeemed_points: "Điểm đã đổi",
    messages: "tin nhắn",
    total_item_price: "Tổng giá trị hàng hóa",
    total_price: "Tổng giá trị đơn hàng",
    total_shipping_price: "Phí vận chuyển",
    available_deliveries: "Khung giờ giao hàng  ",
    hide_items: "Ẩn chi tiết",
    shipping_address: "Địa chỉ giao hàng",
    show_items: "Xem chi tiết",
    view_invoice: "Xem hóa đơn",
    print_invoice: "In hóa đơn",
    generate_invoice_of_order: "Tạo hóa đơn",
    change_status: "Cập nhật tình trạng đơn hàng",
    change: "Cập nhật",
    submit: "Gửi",
    optional: "(không bắt buộc)",
    tracking_number: "Số vận đơn",
    tracking_number_placeholder: "Nhập số vận đơn",
    tracking_placeholder: "Nhập đường link theo dõi tình trạng đơn hàng",
    tracking_url: "Link tra cứu",
    update_tracting_info: "Cập nhật thông tin tra cứu vận đơn",
    confirm: "Xác nhận",
    reset_shipping_fee: "Thiết lập lại phí vận chuyển",
    reseting: "Đang thiết lập lại",
    select_shipping_company: "Chọn công ty vận chuyển",
    operation_successfull: "Thao tác thành công",
    user_profile: "Thiết lập hồ sơ",
    change_password: "Đổi mật khẩu tài khoản",
    change_profile: "Chỉnh sửa hồ sơ",
    update_profile_picture: "Đổi ảnh đại diện",
    phone_number: "Điện thoại",
    updating: "Đang cập nhật",
    shop_info: "Thông tin gian hàng",
    edit_shop: "Chỉnh sửa gian hàng",
    shop_name: "Tên gian hàng",
    no_of_orders: "Số đơn hàng",
    shop_active: "Đang hoạt động",
    shop_address: "Địa chỉ",
    shop_country: "Quốc gia",
    shop_facebook_link: "Facebook",
    selling_price: "Giá bán",
    shop_introduction: "Thông tin gian hàng",
    shop_phone_number: "Điện thoại",
    enter_variation_price: "Giá bán",
    confirm_your_action: "Xác nhận",
    shop_postal_code: "Mã bưu chính",
    shop_tiktok_link: "Tiktok",
    shop_no_of_users: "Số tài khoản truy cập",
    please_confirm_your_action: "Hãy xác nhận thao tác",
    cool_shipping_fee: "Phí gửi hàng trữ mát",
    dry_shipping_fee: "Phí gửi hàng khô",
    from_area: "Nơi gửi",
    frozen_shipping_fee: "Phí gửi hàng trữ đông",
    to_area: "Nơi đến",
    weight: "Trọng lượng",
    actions: "Thao tác",
    approved: "Đã phê duyệt",
    created: "Ngày tạo",
    pending: "Đang chờ phê duyệt",
    seller_email: "Email",
    seller_name: "Tên",
    seller_phone: "Điện thoại",
    seller_id: "Số ID Người bán",
    seller_role: "Vai trò",
    stock: "Tồn kho",
    id: "Số ID",
    recommended: "Được đề xuất",
    sale: "Giảm giá",
    expiry_date: "Ngày hết HSD",
    items_count: "Số lượng mặt hàng",
    date: "Ngày",
    payment_method: "Phương thức thanh toán",
    status: "Tình trạng",
    address: "Địa chỉ",
    role: "Vai trò",
    convenience_store: "Cửa hàng tiện lợi",
    cash_on_delivery: "Thanh toán khi nhận hàng",
    credit_card: "Thẻ tín dụng",
    confirm_password: "Xác nhận mật khẩu",
    new_password: "Mật khẩu mới",
    old_password: "Mật khẩu cũ",
    new_password_is_required: "Mật khẩu mới là bắt buộc",
    old_password_is_required: "Mật khẩu cũ là bắt buộc",
    password_expired_confirmation:
      "Mật khẩu của bạn đã hết hạn. Vui lòng thay đổi mật khẩu để tiếp tục",
    password_8_char: "Mật khẩu phải có ít nhất 8 ký tự",
    password_regex:
      "Mật khẩu phải chứa ít nhất một chữ hoa, một chữ thường, một số và một ký tự đặc biệt",
    passwords_do_not_match: "Mật khẩu không khớp",
    edit_shop_legal_info: "Chỉnh sửa thông tin pháp lý của gian hàng",
    order_review: "Đánh giá đơn hàng",
    review: "Ôn tập",
    cancelled: "Đã hủy",
    rating: "Xếp hạng",
    with_tax: "(có thuế)",
    you: "anh",
    no_item_variations: "Không có phân loại theo trọng lượng",
    shop_registration_number: "Số đăng ký cửa hàng",
    discount: "Giảm giá",
    tax: "Thuế",
    add_images: "Thêm hình ảnh",
    update_address: "cập nhật địa chỉ",
    my_recommended_items: "Mục đề xuất của tôi",
    total_orders: "Tổng số đơn đặt hàng",
    total_revenue: "Tổng doanh thu (tạm tính)",
    view_orders: "Xem đơn hàng",
    critical_items: "Quan trọng",
    search_by_name_or_description: "Tìm kiếm theo tên hoặc mô tả",
    updated: "Cập nhật gần đây",
    added: "Đăng lên gần đây",
    item_information: "Mục thông tin",
    item_category: "Hạng mục",
    item_weight: "Trọng lượng (kg)",
    sku: "Mã phân loai SKU",
    manufacture_date: "ngày sản xuất",
    item_name: "Tên",
    item_description: "Chi tiết",
    order_search_placeholder: "Tìm kiếm đơn hàng",
    reset: "cài lại",
    start_date: "Ngày bắt đầu",
    end_date: "Ngày cuối",
    apply: "áp dụng",
    select: "lựa chọn",
    waiting_delivery: "Đang chờ giao hàng",
    order_id: "Id đơn hàng",
    order_date: "Ngày đặt hàng",
    delivery_address: "Địa chỉ giao hàng",
    sub_total: "Tổng tiền hàng",
    total_for: "Tổng cộng cho",
    ship_order: "Vận chuyển đơn hàng",
    total_items: "Tổng số mặn hàng",
    supported_areas: "Khu vực được hỗ trợ",
    close: "Bỏ qua",
    campaigns: "Chương trình tài trợ phí vận chuyển",
    save: "Cứu",
    no_campaigns: "Không có chiến dịch",
    campaign_name: "Tên chiến dịch",
    campaign_discount: "Giảm giá chiến dịch",
    campaign_description: "Mô tả chiến dịch",
    given_by: "Được cho bởi",
    threshold: "Ngưỡng",
    copy: "sao chép mục",
    discount_type: "Loại giảm giá",
    active: "Tích cực",
    disable: "Vô hiệu hóa",
    select_shipping_area: "Chọn khu vực vận chuyển",
    shipping_fee_with_tax: "Phí vận chuyển có thuế",
    shipping_campaign: "CT tài trợ phí vận chuyển",
    terms_condition: "Điều khoản và điều kiện",
    privacy_policy: "Chính sách bảo mật",
    home: "Trang chủ",
    my_items: "Các mặt hàng",
    delete: "Xóa",
    enter_variation_weight: "Trọng lượng",
    enter_variation_stock: "Số tồn kho",
    order_items: "Các mặt hàng đã đặt hàng",
    are_you_sure_you_want_to_delete_this_item:
      "Bạn chắc chắn muốn xóa mặt hàng này?",
    view_all: "Xem tất cả",
    minimum_order_amount: "số tiền đặt hàng tối thiểu",
    discounted_shipping: "Giảm giá vận chuyển",
    discounted_shipping_error_message:
      "Chỉ áp dụng phí vận chuyển ưu đãi cho các mặt hàng có trọng lượng dưới 2 kg.",
  },
  en_US: {
    expired: "Expired",
    in_stock: "In stock",
    no_results: "No results",
    error: "Error",
    notes: "Notes",
    packed: "Packed",
    supported_prefectures: "Supported Prefectures",
    shipping_company: "Shipping Company",
    shipments: "Shipments",
    last_fetched: "Last Fetched",
    delivered_at: "Delivered At",
    last_updated: "Last Updated",
    track_order: "Track Order",
    track_orders: "Track Orders",
    tracking_details: "Tracking Details",
    location: "Location",
    update_tracking_info: "Update Tracking Info",
    ordered_items: "Ordered Items",
    shipping_campaigns: "Shipping Campaigns",
    others: "Others",
    message_not_allowed_message: "YOU CAN'T REPLY TO THIS MESSAGE !",
    view_messages: "View messages",
    expected_delivery_date: "Expected Delivery Date",
    processing: "Processing",
    admin_cancelled: "Admin Cancelled",
    completed: "Completed",
    order_placed: "Order Placed",
    payment_failed: "Payment Failed",
    seller_acknowledged: "Seller Acknowledged",
    shipped: "Shipped",
    pending_change: "Pending Change",
    progress: "Progress",
    add_to_indian_shop: "Add to indian shop",
    add_to_nepal_shop: "Add to nepal shop",
    related_items: "Related Items",
    order_change_request_message:
      "Request to change the order has been sent to the user.",
    order_changes_accepted_message:
      "Changes to the order by user has been accepted.",
    request_change: "Request Change",
    stock_update_desc: " Enter new stock for this item.",
    acknowledge: "Acknowledge",
    order_change_acknowledged_request:
      "This action will request user for further changes in the order.",
    order_change_acknowledged_desc:
      "This action will approve the order change request.",
    update_stock: "Update Stock",
    select_date: "select date",
    thumbnail_error_message: "Please select a thumbnail and try again",
    manage_images: "Manage Images",
    order_items: "Ordered Items",
    camera_permission_message:
      "Sorry, we need camera permissions to make this work!",
    package_image_uploading_message:
      "Please wait while uploading image is completed",
    logout_alert: "Are you sure you want to logout?",
    delivery_update_success_message: "Delivery time updated successfully",
    flat_amount: "Flat Amount",
    flat_discount: "Flat Discount",
    campaign_discount_error: "Flat shipping discount should be greater than 0",
    campaign_shipping_charge_error:
      "Flat shipping charge should be greater than 0",
    campaign_discount_percentage_error: "Discount should be greater than 0",
    reset_company_title: " Are you sure you want to reset this company?",
    reset_company_description: "Select Company to Reset",
    fields_auto_filled: "fields auto filled",
    fetching_address_info: "fetching address info...",
    prefecture_error: "Prefecture for given postal code doesn't match",
    day: "day",
    something_went_wrong: "Something went wrong !!",
    days: "days",
    expiry_threshold: "Expiry Threshold",
    choose_from_gallery: "Choose from gallery",
    open_camera: "Open Camera",
    enter_item_description: "Enter Item Description",
    enter_item_name: "Enter Item Name",
    enter_item_stock: "Enter Item Stock",
    enter_item_tags: "Enter Item Tags with comma seperated(,)",
    enter_item_weight: "Enter Item Weight",
    enter_marked_price: "Enter Marked Price",
    enter_selling_price: "Enter Selling Price",
    enter_sku: "Enter SKU",
    default: "Default",
    back: "Back",
    send_link: "Send Link",
    clear_filters: "Clear Filters",
    minimum_order_amount: "Minimum Order Amount",
    copy: "Copy",
    view_all: "View All",
    delivery_time_slots: "Delivery Time Slots",
    download: "Download",
    update_address: "Update Address",
    Loading: "Loading...",
    send_message: "Send Message",
    low_stock_threshold: "Low Stock Threshold",
    update_profile: "Update Profile",
    available_delivery_time: "Available Delivery Time",
    variation_name: "Variation Name",
    promotional_message: "Promotional Message",
    enter_variation_stock: "Enter Variation Stock",
    enter_variation_weight: "Enter Variation Weight",
    alert_seller: "You have requested user to update their shipping address",
    enter_variation_name: "Enter Variation Name",
    are_you_sure_you_want_to_delete_this_item:
      "Are you sure you want to delete this item?",
    can_be_sent_in_cool_cart: "Can be sent in cool cart?",
    not_confirmed: "Not Confirmed",
    selected: "Selected",
    disabled: "Disabled",
    sent_by_admin: "Sent by admin",
    edit_message: "Edit Message",
    exp_date: "Exp Date",
    mfg_date: "Mfg Date",
    message_user: "Message User",
    message: "Message",
    order_amount_threshold: "Order Amount Threshold",
    enabled: "Enabled",
    item_status: "Item Status",
    cannot_reply: "You cannot reply to this order now",
    type_here_to_reply: "Type here to reply...",
    order: "Order",
    item_variations: "ITEM VARIATIONS",
    send_message_to_user: "Send message to user",
    shop_registration_number: "Registration No.",
    marked_price_header: "Marked Price",
    price_header: "Price",
    available_deliveries: "Available Deliveries",
    add_item_variation: "Add Item Variation",
    items: "Items",
    welcome_text: "Welcome to the seller panel",
    login: "Login",
    email: "Email",
    password: "Password",
    email_required: "Email is required",
    password_required: "Password is required",
    shipping_fees: "Shipping Fee",
    shop_users: "Users",
    edit: "EDIT",
    update_variation: "Update Variation",
    transaction_type: "Transaction Type",
    logout: "Logout",
    recommended_items: "Recommended Items",
    low_stock_items: "Low Stock Items",
    expired_items: "Expired Items",
    packages: "PACKAGES",
    search_items: "Search By Name or Description",
    category: "Category",
    campaigns: "Campaigns",
    rows_per_page: "Rows per page: ",
    total: "Total",
    before_tax: "Before Tax",
    clear: "Clear",
    profile: "PROFILE",
    recent_messages: "Recent Messages",
    no_message_availabe_for_this_shop: "NO MESSAGE AVAILABLE FOR THIS SHOP",
    english_item_name_required: "English Item Name is required",
    english_item_description_required: "English Item Description is required",
    english_item_shipping_time_required:
      "English Item Shipping Time is required",
    alert_user: "User has requested to update their shipping address",
    ne_item_name_required: "Nepali Item Name is required",
    ne_item_description_required: "Nepali Item Description is required",
    ne_item_shipping_time_required: "Nepali Item Shipping Time is required",
    jp_item_name_required: "Japanese Item Name is required",
    jp_item_description_required: "Japanese Item Description is required",
    jp_item_shipping_time_required: "Japanese Item Shipping Time is required",
    vn_item_name_required: "Vietnamese Item Name is required",
    vn_item_description_required: "Vietnamese Item Description is required",
    vn_item_shipping_time_required: "Vietnamese Item Shipping Time is required",
    item_stock_negative: "Item Stock cannot be negative",
    item_price_negative: "Item Price cannot be negative",
    item_price_required: "Item Price is required",
    item_expired_date_required: "Item Expiration Date is required",
    item_manufactured_date_required: "Item Manufactured Date is required",
    item_category_required: "Item Category is required",
    item_type_required: "Item Type is required",
    item_weight_negative: "Item Weight cannot be negative",
    item_weight_error_message: "Weight shouldn't be greater than 25",
    item_weight_required: "Item Weight is required",
    item_image_length: "Item images cannot be more than 4",
    item_marked_price_negative: "Marked Price cannot be negative",
    item_marked_price_less_than_price:
      "Marked Price can't be less than selling price",
    item_marked_price_zero: "Item marked price cannot be zero",
    en_item_name: "English Item Name",
    total_weight: "Total Weight",
    en_item_name_placeholder: "Enter English Item Name",
    en_shipping_time: "English Shipping Time",
    en_shipping_time_placeholder: "Enter English Shipping Time",
    en_tags: "English Tags",
    en_tags_placeholder: "Enter English Tags",
    en_description: "English Description",
    en_description_placeholder: "Enter English Description",
    ne_item_name: "Nepali Item Name",
    ne_item_name_placeholder: "Enter Nepali Item Name",
    ne_shipping_time: "Nepali Shipping Time",
    ne_shipping_time_placeholder: "Enter Nepali Shipping Time",
    ne_tags: "Nepali Tags",
    ne_tags_placeholder: "Enter Nepali Tags",
    ne_description: "Nepali Description",
    ne_description_placeholder: "Enter Nepali Description",
    jp_item_name: "Japanese Item Name",
    jp_item_name_placeholder: "Enter Japanese Item Name",
    jp_shipping_time: "Japanese Shipping Time",
    jp_shipping_time_placeholder: "Enter Japanese Shipping Time",
    jp_tags: "Japanese Tags",
    jp_tags_placeholder: "Enter Japanese Tags",
    jp_description: "Japanese Description",
    add_variation: "Add Variation",
    jp_description_placeholder: "Enter Japanese Description",
    vn_item_name: "Vietnamese Item Name",
    vn_item_name_placeholder: "Enter Vietnamese Item Name",
    vn_shipping_time: "Vietnamese Shipping Time",
    vn_shipping_time_placeholder: "Enter Vietnamese Shipping Time",
    vn_tags: "Vietnamese Tags",
    item_tags: "Item Tags (Optional)",
    vn_tags_placeholder: "Enter Vietnamese Tags",
    vn_description: "Vietnamese Description",
    vn_description_placeholder: "Enter Vietnamese Description",
    en: "English",
    en_placeholder: "Enter Details in English",
    np: "Nepali",
    np_placeholder: "Enter Details in Nepali",
    jp: "Japanese",
    jp_placeholder: "Enter Details in Japanese",
    vn: "Vietnamese",
    vn_placeholder: "Enter Details in Vietnamese",
    item_price: "Item Price",
    is_discounted_price: "Is this discounted Price?",
    item_marked_price: "Marked Price (Tax Included)",
    item_marked_price_without_tax: "Marked Price (Tax Excluded)",
    item_stock: "Item Stock",
    can_be_merged: "Can be sent in cool cart?",
    select_here: "Select Here",
    yes: "Yes",
    you: "you",
    deleting: "deleting",
    uploading: "uploading",
    no: "No",
    add_images: "Add Images",
    item_expired_date: "Expiry Date",
    item_expired_date_placeholder: "Enter Item Expiry Date",
    item_manufactured_date: "Manufacture Date",
    item_manufactured_date_placeholder: "Enter Item Manufactured Date",
    item_sku: "SKU",
    item_sku_placeholder: "Enter Item SKU",
    item_weight_in_kg: "Weight (in KG)",
    item_weight_in_kg_placeholder: "Enter Item Weight in KG",
    select_category: "Select Category",
    cool: "Cool",
    dry: "Dry",
    frozen: "Frozen",
    item_type: "Item Type",
    choose_image: "Choose Image",
    enter_your_message: "Enter Your Message",
    uplaod_image: "Upload Image",
    update: "Update",
    add: "Add",
    update_item: "Update Item",
    add_item: "Add Item",
    update_thumbnail: "Update Thumbnail",
    delete_item: "Delete Item",

    delete_item_confirmation: "Are you sure you want to delete this item ?",
    delete_item_success_message: "Item deleted successfully",
    recommended_items_add_success_message:
      "Recommended Items added successfully",
    recommended_items_remove_success_message:
      "Recommended Items removed successfully",
    recommended_confirmation_message:
      "Are you sure you want to add this item to recommended items ?",
    recommended__remove_confirmation_message:
      "Are you sure you want to remove this item from recommended items ?",
    confirm_message: "Please confirm your action",
    total_packages: "Total Packages",
    add_package: "Add Package",
    messages: "MESSAGES",
    delete_package: "Delete Package",
    search: "Search",
    package_description: "Package Description",
    package_name: "Package Name",
    package_price: "Package Price",
    select_package_quantity: "Select quantity for ",
    filter: "Filter",
    select_shop: "Select Shop",
    select_language: "Select Language",
    english: "English",
    nepali: "Nepali",
    japanese: "Japanese",
    vietnamese: "Vietnamese",
    description: "Description",
    marked_price: "Marked Price",
    name: "Name",
    edit_variation: "Edit Variation",
    price: "Price",
    item_price_after_tax: "Price (Tax Included)",
    item_price_before_tax: "Price (Tax Excluded)",
    shipping_time: "Shipping Time",
    tags: "Tags",
    type: "Type",
    weight_in_kg: "Weight in KG",
    comments: "Comments",
    waiting: "Waiting",
    comment: "Comment",
    comment_placeholder: "Enter Comment",
    comment_required: "Comment is required",
    forgot_password: "Forgot Password?",
    orders: "Orders",
    order_id_search: "Search by Order Id",
    view: "View",
    enter_your_comment: "Enter Your Comment...",
    low_stock: "Low stock",
    quantity: "Quantity",
    order_info: "Order Info",
    address1: "Address 1",
    address2: "Address 2",
    city: "City",
    delivery_time: "Delivery Time",
    extra_fee: "Extra Fee",
    order_type: "Order Type",
    customer_name: "Customer's Name",
    customer_phone: "Customer's Phone",
    order_status: "Order Status",
    payment_type: "Payment Type",
    postal_code: "Postal Code",
    prefecture: "Prefecture",
    redeemed_points: "Points Redeemed",
    total_item_price: "Total Item Price",
    total_price: "Total Price",
    total_shipping_price: "Total Shipping Price",
    hide_items: "Hide Items",
    shipping_address: "Shipping Address",
    show_items: "Show Items",
    view_invoice: "View Invoice",
    print_invoice: "Print Invoice",
    generate_invoice_of_order: "Generate Invoice of Order",
    change_status: "Change Status",
    address_update_request: "Address Update Request",
    change: "Change",
    submit: "Submit",
    variation_price: "Variation Price",
    variation_stock: "Variation Stock",
    variation_weight: "Variation Weight",
    tracking_number: "Tracking Number",
    tracking_number_placeholder: "Enter Tracking Number",
    tracking_placeholder: "Enter Tracking URL",
    tracking_url: "Tracking URL",
    update_tracting_info: "Update Tracking Info",
    confirm: "Confirm",
    reset_shipping_fee: "Reset Shipping Fee",
    reseting: "Reseting",
    select_shipping_company: "Select shipping company",
    operation_successfull: "Operation Successfull",
    user_profile: "User Profile",
    no_item_variations: "NO ITEM VARIATIONS",
    change_password: "Change Password",
    change_profile: "Change Profile ",
    update_profile_picture: "Update Profile Picture",
    phone_number: "Phone No.",
    updating: "Updating",
    shop_info: "Shop Info",
    edit_shop: "Edit Shop",
    shop_name: "Shop Name",
    no_of_orders: "No of Orders",
    shop_active: "Shop Active",
    shop_address: "Shop Address",
    shop_country: "Shop Country",
    shop_facebook_link: "Facebook Link",
    shop_introduction: "Shop Introduction",
    shop_phone_number: "Shop Phone Number",
    alcohol: "Alcohol",
    shop_postal_code: "Shop Postal Code",
    shop_tiktok_link: "Tiktok Link",
    shop_no_of_users: "Shop No of Users",
    max_quantity: "Max Quantity",
    please_confirm_your_action: "Please confirm your action",
    cool_shipping_fee: "Cool Shipping Fee",
    dry_shipping_fee: "Dry Shipping Fee",
    from_area: "From Area",
    frozen_shipping_fee: "Frozen Shipping Fee",
    to_area: "To Area",
    weight: "Weight",
    actions: "Actions",
    approved: "Approved",
    created: "Created",
    pending: "Pending",
    seller_email: "Seller Email",
    seller_name: "Seller Name",
    seller_phone: "Seller Phone",
    seller_id: "Seller Id",
    seller_role: "Seller Role",
    stock: "Stock",
    id: "Id",
    recommended: "Recommended",
    sale: "Sale",
    expiry_date: "Expiry Date",
    items_count: "Items Count",
    date: "Date",
    payment_method: "Payment Method",
    status: "Status",
    address: "Address",
    try_changing_shop: "TRY CHANGING SHOP",
    role: "Role",
    filter_by_status: "Filter by Status",
    cancelled: "Cancelled",
    admin_cancel: "Admin Cancel",
    all: "All",
    enter_variation_price: "Enter Variation Price",
    all_items: "All Items",
    cancel: "Cancel",
    done: "Done",
    pay_pay: "Pay Pay",
    processed: "Processed",
    wait_payment: "Waiting For Payment",
    wait_review: "Wait Review",
    wait_shipping: "Wait Shipping",
    convenience_store: "Convinience Store",
    cash_on_delivery: "Cash On Delivery",
    credit_card: "Credit Card",
    confirm_password: "Confirm Password",
    new_password: "New Password",
    old_password: "Old Password",
    new_password_is_required: "New Password is required",
    old_password_is_required: "Old Password is required",
    password_expired_confirmation:
      "Your password has expired. Please change your password to continue",
    password_8_char: "Password must be at least 8 characters",
    password_regex:
      "Password must contain at least one uppercase, one lowercase, one number and one special character",
    passwords_do_not_match: "Passwords do not match",
    edit_shop_legal_info: "Edit Shop Legal Info",
    order_review: "Order Review",
    review: "Review",
    search_messages: "Search Messages",
    rating: "Rating",
    with_tax: "(With Tax)",
    discount: "Discount",
    tax: "Tax",
    my_recommended_items: "My Recommended Items",
    total_orders: "Total Orders",
    total_revenue: "Total Revenue",
    view_orders: "View Orders",
    critical_items: "Critical Items",
    search_by_name_or_description: "Search by name or description",
    updated: "Updated",
    added: "Added",
    item_information: "Item Information",
    item_category: "Item Category",
    item_weight: "Item Weight",
    sku: "SKU",
    manufacture_date: "Manufacture Date",
    item_name: "Item Name",
    item_description: "Item Description",
    order_search_placeholder: "Search for an order",
    reset: "Reset",
    optional: "Optional",
    start_date: "Start Date",
    end_date: "End Date",
    apply: "Apply",
    select: "Select",
    waiting_delivery: "Waiting Delivery",
    order_id: "Order ID",
    order_date: "Order Date",
    delivery_address: "Delivery Address",
    sub_total: "Sub-Total",
    total_for: "Total For",
    ship_order: "Ship Order",
    total_items: "Total Items",
    supported_areas: "Supported Areas",
    close: "Close",
    save: "Save",
    no_campaigns: "No Campaigns",
    campaign_name: "Campaign Name",
    campaign_discount: "Campaign Discount",
    campaign_description: "Campaign Description",
    given_by: "Given By",
    threshold: "Threshold",
    discount_type: "Discount Type",
    active: "Active",
    disable: "Disable",
    select_shipping_area: "Select Shipping Area",
    shipping_fee_with_tax: "Shipping Fee With Tax",
    shipping_campaign: "Shipping Campaign",
    terms_condition: "Terms & Conditions",
    privacy_policy: "Privacy & Policy",
    home: "HOME",
    my_items: "My Items",
    confirm_your_action: "Confirm your action",
    selling_price: "Selling Price",
    delete: "Delete",
    enter_tracking_number: "Enter Tracking Number",
    enter_tracking_url: "Enter Tracking Url",
    change_langauge: "Change Langauge",
    approve: "Approve",
    discounted_shipping: "Discounted Shipping",
    discounted_shipping_error_message:
      "Discounted shipping is only available for items with weight up to 2 kg",
  },
  ne_NP: {
    waiting: "पर्खँदै",
    in_stock: "स्टकमा छ",
    expired: "म्याद सकिएको",
    no_results: "कुनै परिणामहरू छैनन्",
    error: "गलती",
    supported_prefectures: "समर्थित क्षेत्रहरू",
    packed: "प्याक गरिएको",
    notes: "नोटहरू",
    shipping_company: "ढुवानी कम्पनी",
    shipments: "ढुवानीहरू",
    last_updated: "पछिल्लो अपडेट",
    delivered_at: "डेलिभरी दिन",
    last_fetched: "पछिल्लो पटक ल्याइयो",
    track_order: "ट्र्याक अर्डर",
    track_orders: "ट्र्याक अर्डरहरू",
    tracking_details: "ट्र्याकिङ विवरणहरू",
    location: "स्थान",
    update_tracking_info: "ट्र्याकिङ जानकारी अपडेट गर्नुहोस्",
    ordered_items: "अर्डर गरिएका वस्तुहरू",
    shipping_campaigns: "ढुवानी अभियानहरू",
    others: "अरू",
    message_not_allowed_message: "तपाईं यो सन्देशको जवाफ दिन सक्नुहुन्न!",
    view_messages: "सन्देशहरू हेर्नुहोस्",
    expected_delivery_date: "अपेक्षित डेलिभरि न्हिल्याः",
    processing: "प्रशोधन गर्दै",
    admin_cancelled: "व्यवस्थापक रद्द गरियो",
    shipped: "पठाइयो",
    completed: "पूरा भयो",
    order_placed: "अर्डर राखियो",
    payment_failed: "भुक्तानी असफल भयो",
    seller_acknowledged: "विक्रेता स्वीकार गरियो",
    pending_change: "विचाराधीन परिवर्तन",
    progress: "प्रगति",
    add_to_indian_shop: "भारतीय पसलमा थप्नुहोस्",
    add_to_nepal_shop: "नेपाल पसलमा थप्नुहोस्",
    related_items: "सम्बन्धित वस्तुहरू",
    order_change_request_message:
      "अर्डर परिवर्तन गर्न अनुरोध प्रयोगकर्तालाई पठाइएको छ।",
    order_changes_accepted_message:
      "प्रयोगकर्ता द्वारा अर्डरमा परिवर्तनहरू स्वीकार गरिएको छ।",
    stock_update_desc: "यो वस्तुको लागि नयाँ स्टक प्रविष्ट गर्नुहोस्।",
    acknowledge: "स्वीकार गर्नुहोस्",
    request_change: "परिवर्तन अनुरोध गर्नुहोस्",
    order_change_acknowledged_request:
      "यो कार्यले प्रयोगकर्तालाई अर्डरमा थप परिवर्तनहरूको लागि अनुरोध गर्नेछ।",
    order_change_acknowledged_desc:
      "यो कार्यले अर्डर परिवर्तन अनुरोध स्वीकृत गर्नेछ।",
    update_stock: "स्टक अद्यावधिक गर्नुहोस्",
    select_date: "मिति चयन गर्नुहोस्",
    thumbnail_error_message:
      "कृपया थम्बनेल चयन गर्नुहोस् र पुन: प्रयास गर्नुहोस्",
    manage_images: "छविहरू प्रबन्ध गर्नुहोस्",
    camera_permission_message:
      "माफ गर्नुहोस्, हामीलाई यो काम गर्न क्यामेरा अनुमति चाहिन्छ!",
    deleting: "मेटाउँदै",
    uploading: "अपलोड गर्दै",
    item_weight_error_message: "वजन 25 भन्दा बढी हुनु हुँदैन",
    package_image_uploading_message:
      "छवि अपलोड पूरा हुँदा कृपया प्रतीक्षा गर्नुहोस्",
    delivery_update_success_message: "डेलिभरी समय सफलतापूर्वक अपडेट गरियो",
    logout_alert: "के तपाइँ निश्चित हुनुहुन्छ कि तपाइँ लगआउट गर्न चाहनुहुन्छ?",
    flat_discount: "फ्ल्याट छुट",
    flat_amount: "समतल रकम",
    campaign_discount_error: "फ्ल्याट ढुवानी छुट ० भन्दा बढी हुनुपर्छ",
    campaign_shipping_charge_error: "फ्ल्याट ढुवानी शुल्क ० भन्दा बढी हुनुपर्छ",
    campaign_discount_percentage_error: "छुट ० भन्दा बढी हुनुपर्छ",
    reset_company_description:
      "के तपाइँ यो कम्पनी रिसेट गर्न निश्चित हुनुहुन्छ?",
    reset_company_title: "रिसेट गर्न कम्पनी चयन गर्नुहोस्",
    fields_auto_filled: "फिल्डहरू स्वत: भरियो",
    fetching_address_info: "ठेगाना जानकारी प्राप्त गर्दै...",
    prefecture_error: "दिइएको हुलाक कोडको लागि प्रिफेक्चर मेल खाँदैन",
    day: "दिन",
    something_went_wrong: "केहि गलत भयो !!",
    days: "दिनहरू",
    expiry_threshold: "म्याद सकिने थ्रेसहोल्ड",
    approve: "अनुमोदन",
    choose_from_gallery: "ग्यालरीबाट छान्नुहोस्",
    open_camera: "क्यामेरा खोल",
    enter_item_description: "वस्तु विवरण प्रविष्ट गर्नुहोस्",
    enter_item_name: "वस्तुको नाम प्रविष्ट गर्नुहोस्",
    enter_item_stock: "वस्तु स्टक प्रविष्ट गर्नुहोस्",
    enter_item_tags:
      "अल्पविरामबाट अलग गरिएको वस्तु ट्यागहरू प्रविष्ट गर्नुहोस् (,)",
    enter_item_weight: "वस्तुको वजन प्रविष्ट गर्नुहोस्",
    enter_marked_price: "चिन्हित मूल्य प्रविष्ट गर्नुहोस्",
    enter_selling_price: "बिक्री मूल्य प्रविष्ट गर्नुहोस्",
    enter_sku: "Sku प्रविष्ट गर्नुहोस्",
    enter_tracking_url: "ट्र्याकिङ url प्रविष्ट गर्नुहोस्",
    enter_tracking_number: "ट्र्याकिङ नम्बर प्रविष्ट गर्नुहोस्",
    default: "पूर्वनिर्धारित",
    back: "पछाउनुहोस्",
    send_link: "लिङ्क पठाउनुहोस्",
    change_langauge: "भाषा परिवर्तन गर्नुहोस्",
    update_profile: "प्रोफाइल अपडेट गर्नुहोस्",
    delivery_time_slots: "डेलिभरी समय स्लटहरू",
    download: "डाउनलोड गर्नुहोस्",
    Loading: "लोड गर्दै...",
    send_message: "सन्देश पठाउनुहोस्",
    optional: "वैकल्पिक",
    search_messages: "सन्देशहरू खोज्नुहोस्",
    address_update_request: "ठेगाना अद्यावधिक अनुरोध",
    selling_price: "बिक्री मूल्य",
    not_confirmed: "पुष्टि भएको छैन",
    selected: "चयन गरिएको",
    confirm_your_action: "आफ्नो कार्य पुष्टि गर्नुहोस्",
    disabled: "अक्षम",
    edit: "सम्पादन गर्नुहोस्",
    order_amount_threshold: "अर्डर रकम थ्रेसहोल्ड",
    sent_by_admin: `व्यवस्थापक द्वारा पठाइएको`,
    edit_message: "सन्देश सम्पादन",
    message: "सन्देश",
    enabled: "सक्षम गरिएको",
    add_images: "छविहरू थप्नुहोस्",
    low_stock_threshold: "कम स्टक थ्रेसहोल्ड",
    type_here_to_reply: "जवाफ दिन यहाँ टाइप गर्नुहोस्...",
    total_weight: "जम्मा तौल",
    cannot_reply: "तपाईं अहिले यो अर्डर जवाफ दिन सक्नुहुन्न",
    send_message_to_user: "प्रयोगकर्तालाई सन्देशहरू पठाउनुहोस्",
    shop_registration_number: "स्टोर दर्ता नम्बर",
    item_price_after_tax: "मूल्य (कर समावेश)",
    marked_price_header: "मार्केड मूल्य",
    item_status: "वस्तु स्थिति",
    price_header: "मूल्य",
    recent_messages: "भर्खरका सन्देशहरू",
    items: "वस्तुहरू",
    welcome_text: "बिक्रेता प्यानलमा आफ्नो स्वागत छ",
    login: "लगइन",
    email: "ईमेल",
    password: "पासवर्ड",
    promotional_message: "प्रचार सन्देश",
    email_required: "ईमेल आवश्यक छ",
    password_required: "पासवर्ड आवश्यक छ",
    shipping_fees: "शिपिंग शुल्क",
    enter_variation_weight: "भिन्नता वजन प्रविष्ट गर्नुहोस्",
    alcohol: "रक्सी",
    shop_users: "दुकान प्रयोगकर्ताहरू",
    logout: "लगआउट",
    recommended_items: "सिफारिस गर्नुभयो वस्तुहरू",
    low_stock_items: "कम भण्डार वस्तुहरू",
    expired_items: "समय सीमा समाप्त वस्तुहरू",
    packages: "प्याकेजहरू",
    search_items: "नाम वा वर्णन द्वारा खोज्नुहोस्",
    category: "श्रेणी",
    rows_per_page: "प्रति पृष्ठ पंक्तिहरू: ",
    no_item_variations: "कुनै वस्तु भिन्नता छैन",
    total: "कुल",
    enter_your_comment: "आफ्नो टिप्पणी प्रविष्ट गर्नुहोस्...",
    you: "तिमी",
    messages: "सन्देशहरू",
    update_address: "ठेगाना अपडेट गर्नुहोस्",
    available_delivery_time: "उपलब्ध वितरण समय",
    can_be_sent_in_cool_cart: "कूल कार्टमा पठाउन सकिन्छ?",
    english_item_name_required: "अंग्रेजी वस्तुको नाम आवश्यक छ",
    english_item_description_required: "अंग्रेजी वस्तुको वर्णन आवश्यक छ",
    english_item_shipping_time_required: "अंग्रेजी वस्तुको शिपिंग समय आवश्यक छ",
    ne_item_name_required: "नेपाली वस्तुको नाम आवश्यक छ",
    ne_item_description_required: "नेपाली वस्तुको वर्णन आवश्यक छ",
    ne_item_shipping_time_required: "नेपाली वस्तुको शिपिंग समय आवश्यक छ",
    minimum_order_amount: "न्यूनतम अर्डर रकम",
    jp_item_name_required: "जापानी वस्तुको नाम आवश्यक छ",
    jp_item_description_required: "जापानी वस्तुको वर्णन आवश्यक छ",
    transaction_type: "लेनदेन प्रकार",
    item_tags: "वस्तु ट्याग (वैकल्पिक)",
    max_quantity: "अधिकतम मात्रा",
    jp_item_shipping_time_required: "जापानी वस्तुको शिपिंग समय आवश्यक छ",
    vn_item_name_required: "भियतनामी वस्तुको नाम आवश्यक छ",
    vn_item_description_required: "भियतनामी वस्तुको वर्णन आवश्यक छ",
    vn_item_shipping_time_required: "भियतनामी वस्तुको शिपिंग समय आवश्यक छ",
    item_stock_negative: "वस्तु भण्डार नकारात्मक हुँदैन",
    item_price_negative: "वस्तु मूल्य नकारात्मक हुँदैन",
    item_price_required: "वस्तु मूल्य आवश्यक छ",
    item_expired_date_required: "वस्तु समय सीमा आवश्यक छ",
    item_manufactured_date_required: "वस्तु निर्माण मिति आवश्यक छ",
    item_category_required: "वस्तु श्रेणी आवश्यक छ",
    item_type_required: "वस्तु प्रकार आवश्यक छ",
    edit_variation: "भिन्नता सम्पादन गर्नुहोस्",
    item_weight_negative: "वस्तु तौल नकारात्मक हुँदैन",
    item_weight_required: "वस्तु तौल आवश्यक छ",
    are_you_sure_you_want_to_delete_this_item:
      "के तपाइँ यो वस्तु मेटाउन निश्चित हुनुहुन्छ?",
    item_image_length: "वस्तु तस्वीरहरू 4 भन्दा बढी हुन सक्दैन",
    item_marked_price_negative: "वस्तु चिन्हित मूल्य नकारात्मक हुँदैन",
    item_marked_price_less_than_price:
      "चिन्हित मूल्य बिक्री मूल्य भन्दा कम हुन सक्दैन",
    item_marked_price_zero: "वस्तु चिन्हित मूल्य 0 हुन सक्दैन",
    add_variation: "भिन्नता थप्नुहोस्",
    update_variation: "भिन्नता अपडेट गर्नुहोस्",
    en_item_name: "अंग्रेजी वस्तुको नाम",
    en_item_name_placeholder: "अंग्रेजी वस्तुको नाम लेख्नुहोस्",
    en_shipping_time: "अंग्रेजी शिपिंग समय",
    en_shipping_time_placeholder: "अंग्रेजी शिपिंग समय लेख्नुहोस्",
    en_tags: "अंग्रेजी ट्यागहरू",
    en_tags_placeholder: "अंग्रेजी ट्यागहरू लेख्नुहोस्",
    en_description: "अंग्रेजी वर्णन",
    en_description_placeholder: "अंग्रेजी वर्णन लेख्नुहोस्",
    ne_item_name: "नेपाली वस्तुको नाम",
    enter_your_message: "आफ्नो सन्देश प्रविष्ट गर्नुहोस्",
    ne_item_name_placeholder: "नेपाली वस्तुको नाम लेख्नुहोस्",
    ne_shipping_time: "नेपाली शिपिंग समय",
    ne_shipping_time_placeholder: "नेपाली शिपिंग समय लेख्नुहोस्",
    ne_tags: "नेपाली ट्यागहरू",
    copy: "कापी",
    clear_filters: "फिल्टरहरू खाली गर्नुहोस्",
    item_variations: "वस्तु भिन्नता",
    alert_user:
      "प्रयोगकर्ताले आफ्नो ढुवानी ठेगाना अद्यावधिक गर्न अनुरोध गरेको छ",
    ne_tags_placeholder: "नेपाली ट्यागहरू लेख्नुहोस्",
    ne_description: "नेपाली वर्णन",
    ne_description_placeholder: "नेपाली वर्णन लेख्नुहोस्",
    jp_item_name: "जापानी वस्तुको नाम",
    jp_item_name_placeholder: "जापानी वस्तुको नाम लेख्नुहोस्",
    alert_seller:
      "तपाईंले प्रयोगकर्तालाई उनीहरूको ढुवानी ठेगाना अद्यावधिक गर्न अनुरोध गर्नुभएको छ",
    jp_shipping_time: "जापानी शिपिंग समय",
    jp_shipping_time_placeholder: "जापानी शिपिंग समय लेख्नुहोस्",
    jp_tags: "जापानी ट्यागहरू",
    jp_tags_placeholder: "जापानी ट्यागहरू लेख्नुहोस्",
    jp_description: "जापानी वर्णन",
    jp_description_placeholder: "जापानी वर्णन लेख्नुहोस्",
    vn_item_name: "भियतनामी वस्तुको नाम",
    vn_item_name_placeholder: "भियतनामी वस्तुको नाम लेख्नुहोस्",
    vn_shipping_time: "भियतनामी शिपिंग समय",
    vn_shipping_time_placeholder: "भियतनामी शिपिंग समय लेख्नुहोस्",
    message_user: "प्रयोगकर्तालाई सन्देश पठाउनुहोस्",
    vn_tags: "भियतनामी ट्यागहरू",
    vn_tags_placeholder: "भियतनामी ट्यागहरू लेख्नुहोस्",
    vn_description: "भियतनामी वर्णन",
    vn_description_placeholder: "भियतनामी वर्णन लेख्नुहोस्",
    en: "अंग्रेजी",
    en_placeholder: "अंग्रेजीमा विवरण लेख्नुहोस्",
    np: "नेपाली",
    np_placeholder: "नेपालीमा विवरण लेख्नुहोस्",
    jp: "जापानी",
    jp_placeholder: "जापानीमा विवरण लेख्नुहोस्",
    vn: "भियतनामी",
    vn_placeholder: "भियतनामीमा विवरण लेख्नुहोस्",
    item_price: "वस्तु मूल्य",
    is_discounted_price: "के यो छुट मूल्य हो?",
    item_marked_price: "चिन्हित मूल्य",
    item_marked_price_without_tax: "चिन्हित मूल्य (कर अघि)",
    item_stock: "वस्तु स्टक",
    can_be_merged: "के यो कूल कार्टमा पठाउन सकिन्छ?",
    select_here: "यहाँ चयन गर्नुहोस्",
    yes: "हो",
    enter_variation_name: "भिन्नता नाम प्रविष्ट गर्नुहोस्",
    enter_variation_price: "भिन्नता मूल्य प्रविष्ट गर्नुहोस्",
    no: "होइन",
    enter_variation_stock: "भिन्नता स्टक प्रविष्ट गर्नुहोस्",
    item_expired_date: "म्याद सकिने मिति",
    item_expired_date_placeholder: "म्याद सकिने मिति लेख्नुहोस्",
    item_manufactured_date: "वस्तु निर्माण मिति",
    item_manufactured_date_placeholder: "वस्तु निर्माण मिति लेख्नुहोस्",
    item_sku: "SKU",
    item_sku_placeholder: "वस्तु SKU लेख्नुहोस्",
    item_weight_in_kg: "वस्तु तौल किलोमा",
    variation_name: "भिन्नता नाम",
    variation_price: "भिन्नता मूल्य",
    variation_stock: "भिन्नता स्टक",
    variation_weight: "भिन्नता वजन",
    item_weight_in_kg_placeholder: "वस्तु तौल किलोमा लेख्नुहोस्",
    select_category: "श्रेणी चयन गर्नुहोस्",
    cool: "ठान्ने",
    dry: "सुख्खा",
    frozen: "जम्मा",
    item_type: "वस्तु प्रकार",
    choose_image: "तस्वीर चयन गर्नुहोस्",
    uplaod_image: "तस्वीर अपलोड गर्नुहोस्",
    update: "अपडेट",
    cancelled: "रद्द गरियो",
    add: "थप्नुहोस्",
    before_tax: "कर अघि",
    update_item: "वस्तु अपडेट गर्नुहोस्",
    add_item: "वस्तु थप्नुहोस्",
    update_thumbnail: "थम्बनेल अपडेट गर्नुहोस्",
    delete_item: "वस्तु मेटाउनुहोस्",
    delete_item_confirmation: "के तपाईं यो वस्तु मेटाउन चाहानुहुन्छ?",
    delete_item_success_message: "वस्तु सफलतापूर्वक मेटियो",
    recommended_items_add_success_message:
      "सिफारिस गरिएको वस्तुहरू सफलतापूर्वक थपियो",
    recommended_items_remove_success_message:
      "सिफारिस गरिएको वस्तुहरू सफलतापूर्वक हटाइयो",
    recommended__remove_confirmation_message:
      "के तपाईं यो वस्तु हटाउन चाहानुहुन्छ?",
    recommended_confirmation_message:
      "के तपाईं यो वस्तु सिफारिस गर्न चाहानुहुन्छ?",
    confirm_message: "कृपया आफ्नो कार्य पुष्टि गर्नुहोस्",
    total_packages: "कुल प्याकेजहरू",
    add_package: "प्याकेज थप्नुहोस्",
    delete_package: "प्याकेज मेटाउनुहोस्",
    search: "खोज्नुहोस्",
    view_all: "सबै हेर्नुहोस्",
    package_description: "प्याकेज वर्णन",
    package_name: "प्याकेज नाम",
    package_price: "प्याकेज मूल्य",
    select_package_quantity: "प्याकेज मात्रा चयन गर्नुहोस्",
    filter: "फिल्टर :,गर्नु,रिसेट",
    select_shop: "दुकान चयन गर्नुहोस्",
    select_language: "भाषा चयन गर्नुहोस्",
    low_stock: "थोरै सामान",
    english: "अंग्रेजी",
    nepali: "नेपाली",
    vietnamese: "भियतनामी",
    japanese: "जापानी",
    campaigns: "अभियानहरू",
    description: "वर्णन",
    marked_price: "चिन्हित मूल्य",
    name: "नाम",
    price: "कर पछि मूल्य",
    item_price_before_tax: "कर अघि मूल्य",
    shipping_time: "शिपिंग समय",
    tags: "ट्यागहरू",
    available_deliveries: "उपलब्ध वितरण",
    type: "प्रकार",
    weight_in_kg: "तौल किलोमा",
    comments: "टिप्पणीहरू",
    comment: "टिप्पणी",
    comment_placeholder: "टिप्पणी लेख्नुहोस्",
    comment_required: "कृपया टिप्पणी लेख्नुहोस्",
    orders: "अर्डरहरू",
    order: "अर्डर",
    order_id_search: "अर्डर आईडी द्वारा खोज्नुहोस्",
    no_message_availabe_for_this_shop: "यस पसलको लागि कुनै सन्देश उपलब्ध छैन",
    view: "हेर्नुहोस्",
    quantity: "मात्रा",
    forgot_password: "पासवर्ड भुल्नु भयो?",
    order_info: "अर्डर जानकारी",
    address1: "ठेगाना 1",
    address2: "ठेगाना 2",
    city: "शहर",
    delivery_time: "डेलिभरी समय",
    extra_fee: "अतिरिक्त शुल्क",
    order_type: "अर्डर प्रकार",
    customer_name: "ग्राहकको नाम",
    customer_phone: "ग्राहकको फोन",
    order_status: "अर्डर स्थिति",
    payment_type: "भुक्तानी प्रकार",
    postal_code: "पोस्टल कोड",
    prefecture: "प्रेफेक्चर",
    order_items: "वस्तुहरू हेर्नुहोस्",
    profile: "प्रोफाइल",
    redeemed_points: "पुरस्कृत अंकहरू",
    total_item_price: "कुल वस्तु मूल्य",
    total_price: "कुल मूल्य",
    total_shipping_price: "कुल शिपिंग मूल्य",
    hide_items: "वस्तुहरू लुकाउनुहोस्",
    shipping_address: "शिपिंग ठेगाना",
    show_items: "वस्तुहरू देखाउनुहोस्",
    view_invoice: "बिल हेर्नुहोस्",
    print_invoice: "बिल प्रिन्ट गर्नुहोस्",
    generate_invoice_of_order: "अर्डरको बिल बनाउनुहोस्",
    change_status: "स्थिति परिवर्तन गर्नुहोस्",
    change: "परिवर्तन",
    add_item_variation: "वस्तु भिन्नता थप्नुहोस्",
    submit: "पेश",
    tracking_number: "ट्र्याकिंग नम्बर",
    tracking_number_placeholder: "ट्र्याकिंग नम्बर लेख्नुहोस्",
    tracking_placeholder: "ट्र्याकिंग यूआरएल लेख्नुहोस्",
    tracking_url: "ट्र्याकिंग यूआरएल",
    update_tracting_info: "ट्र्याकिंग जानकारी अपडेट गर्नुहोस्",
    confirm: "पुष्टि गर्नुहोस्",
    reset_shipping_fee: "शिपिंग शुल्क रिसेट गर्नुहोस्",
    reseting: "रिसेट गर्दै",
    select_shipping_company: "शिपिंग कम्पनी चयन गर्नुहोस्",
    operation_successfull: "कार्य सफल भयो",
    user_profile: "प्रयोगकर्ता प्रोफाइल",
    change_password: "पासवर्ड परिवर्तन गर्नुहोस्",
    change_profile: "प्रोफाइल परिवर्तन गर्नुहोस्",
    update_profile_picture: "प्रोफाइल तस्वीर अपडेट गर्नुहोस्",
    phone_number: "फोन नम्बर",
    try_changing_shop: "पसल परिवर्तन गर्ने प्रयास गर्नुहोस्",
    updating: "अपडेट गर्दै",
    shop_info: "दुकान जानकारी",
    edit_shop: "दुकान सम्पादन गर्नुहोस्",
    no_of_orders: "अर्डरहरूको संख्या",
    shop_active: "दुकान सक्रिय",
    shop_address: "दुकान ठेगाना",
    shop_country: "दुकान देश",
    shop_facebook_link: "दुकान फेसबुक लिंक",
    shop_introduction: "दुकान परिचय",
    shop_name: "दुकानको नाम",
    shop_phone_number: "दुकान फोन नम्बर",
    shop_postal_code: "दुकान पोस्टल कोड",
    shop_tiktok_link: "दुकान टिकटोक लिंक",
    shop_no_of_users: "दुकान प्रयोगकर्ताहरूको संख्या",
    please_confirm_your_action: "कृपया आफ्नो कार्य पुष्टि गर्नुहोस्",
    cool_shipping_fee: "चिसो शिपिंग शुल्क",
    dry_shipping_fee: "सुक्खा शिपिंग शुल्क",
    frozen_shipping_fee: "जमेको शिपिंग शुल्क",
    from_area: "ठेगाना बाट",
    to_area: "ठेगाना सम्म",
    weight: "वजन",
    actions: "कार्यहरू",
    approved: "स्वीकृत",
    created: "सिर्जना ",
    pending: "लक्षित",
    seller_email: "बिक्रेता ईमेल",
    seller_id: "बिक्रेता आईडी",
    seller_name: "बिक्रेता नाम",
    seller_phone: "बिक्रेता फोन",
    seller_role: "बिक्रेता भूमिका",
    stock: "स्टक",
    id: "आईडी",
    delete: "मेटाउन",
    recommended: "सिफारिस गरिएको",
    sale: "सेल",
    expiry_date: "म्याद समाप्ति मिति",
    items_count: "वस्तुहरूको संख्या",
    date: "मिति",
    payment_method: "भुक्तानी विधि",
    status: "स्थिति",
    pay_pay: "Pay Pay",
    address: "ठेगाना",
    role: "भूमिका",
    filter_by_status: "स्थिति अनुसार फिल्टर गर्नुहोस्",
    admin_cancel: "एडमिन रद्द",
    all: "सबै",
    cancel: "रद्द",
    done: "गरियो",
    processed: "प्रसेस ",
    wait_payment: "भुक्तानीको लागि पर्खँदै",
    wait_review: "समीक्षा गर्न प्रतीक्षा",
    wait_shipping: "शिपिंगको लागि प्रतीक्षा",
    convenience_store: "कन्भिनियन्स स्टोर",
    cash_on_delivery: "डेलिभरीमा नगद",
    credit_card: "क्रेडिट कार्ड",
    confirm_password: "पासवर्ड पुष्टि गर्नुहोस्",
    new_password: "नयाँ पासवर्ड",
    new_password_is_required: "नयाँ पासवर्ड आवश्यक छ",
    old_password: "पुरानो पासवर्ड",
    old_password_is_required: "पुरानो पासवर्ड आवश्यक छ",
    password_8_char: "पासवर्ड 8 वर्ण भन्दा बढी हुनुपर्छ",
    password_expired_confirmation:
      "पासवर्ड समय सीमा समाप्त भयो। कृपया पासवर्ड परिवर्तन गर्नुहोस्",
    password_regex:
      "पासवर्डमा कम्तीमा एक बडी अक्षर, एक छोटो अक्षर, एक संख्या र एक विशेष वर्ण अनिवार्य छ",
    passwords_do_not_match: "पासवर्ड मेल खाँदैन",
    edit_shop_legal_info: "दुकानको कानूनी जानकारी सम्पादन गर्नुहोस्",
    order_review: "अर्डर समीक्षा",
    review: "समीक्षा",
    rating: "मूल्याङ्कन",
    with_tax: "(कर सहित)",
    all_items: "सबै वस्तुहरू",
    discount: "छुट",
    tax: "कर",
    my_recommended_items: "मेरा सिफारिस गरिएका वस्तुहरू",
    total_orders: "सबै अर्डर",
    total_revenue: "सबै राजस्व",
    view_orders: "अर्डरहरू हेर्नुहोस्",
    critical_items: "महत्वपूर्ण वस्तुहरू",
    updated: "अपडेटहरू",
    search_by_name_or_description: "नाम वा विवरण द्वारा खोज्नुहोस्",
    added: "नयाँ थपिएको",
    item_information: "वस्तु जानकारी",
    item_category: "वस्तु कोटि",
    item_weight: "वस्तुको वजन",
    sku: "SKU",
    manufacture_date: "निर्माण मिति",
    item_name: "वस्तुको नाम",
    item_description: "वस्तु विवरण",
    order_search_placeholder: "अर्डर खोज्नुहोस्",
    reset: "रिसेट",
    start_date: "सुरू मिति",
    end_date: "अन्त्य मिति",
    clear: "स्पष्ट",
    apply: "निवेदन गर्नु",
    select: "चयन गर्नुहोस्",
    waiting_delivery: "डेलिभरी पर्खँदै",
    order_id: "अर्डर आईडी",
    order_date: "अर्डर मिति",
    delivery_address: "डेलिभरी ठेगाना",
    sub_total: "उप कुल",
    total_for: "को लागि कुल",
    ship_order: "अर्डर पठाउनुहोस्",
    total_items: "कुल वस्तुहरू",
    supported_areas: "समर्थित क्षेत्रहरू",
    close: "बन्द गर्नुहोस्",
    save: "बचत गर्नुहोस्",
    no_campaigns: "कुनै अभियान छैन",
    campaign_name: "अभियानको नाम",
    campaign_discount: "अभियान छुट",
    campaign_description: "अभियान विवरण",
    given_by: "द्वारा दिइएको",
    threshold: "थ्रेसहोल्ड",
    discount_type: "छुट प्रकार",
    active: "सक्रिय",
    disable: "असक्षम",
    select_shipping_area: "ढुवानी क्षेत्र चयन गर्नुहोस्",
    shipping_fee_with_tax: "कर सहित ढुवानी शुल्क",
    shipping_campaign: "ढुवानी अभियान",
    terms_condition: "नियम तथा सर्त",
    privacy_policy: "गोपनीयता र नीति",
    home: "घर",
    my_items: "मेरा वस्तुहरू",
    exp_date: "Exp_date",
    mfg_date: "Mfg_date",
    discounted_shipping: "छूट शिपिंग",
    discounted_shipping_error_message:
      "२ किलोग्रामसम्मको तौल भएका वस्तुहरूको लागि मात्र छुटयुक्त शिपिंग उपलब्ध छ।",
  },
};
